services:
  app:
    build:
      context: .
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_BASE_URL=${API_BASE_URL}
    restart: always
    volumes:
      - .:/app
